-- MySQL Script generated by MySQL Workbench
-- Wed Feb 13 00:58:55 2019
-- Model: Project_1    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Table Customers
-- -----------------------------------------------------

DROP TABLE IF EXISTS Customers CASCADE;

CREATE TABLE IF NOT EXISTS Customers (
  idCustomers  SERIAL,
  CustomerUsername VARCHAR(256) NOT NULL,
  CustomerPassword VARCHAR(256) NOT NULL,
  CustomerEmail VARCHAR(256) NOT NULL,
  Created TIMESTAMP NOT NULL,
  PRIMARY KEY (idCustomers)
);

CREATE UNIQUE INDEX Username_UNIQUE ON Customers (CustomerUsername);
CREATE UNIQUE INDEX Email_UNIQUE ON Customers (CustomerEmail);

-- -----------------------------------------------------
-- Table Products
-- -----------------------------------------------------
DROP TABLE IF EXISTS Products CASCADE;

CREATE TABLE IF NOT EXISTS Products (
  idProducts SERIAL,
  Productimage VARCHAR(32) NOT NULL,
  Catergory VARCHAR(16) NOT NULL,
  Code VARCHAR(64) NOT NULL,
  Brand VARCHAR(64) NULL,
  Price DECIMAL(16,2) NOT NULL,
  Discount VARCHAR(64) NULL,
  Stock VARCHAR(64) NULL,
  LastCount VARCHAR(64) NULL,
  LastOrder TIMESTAMP NULL,
  PRIMARY KEY (idProducts)
);

CREATE UNIQUE INDEX Productimage_UNIQUE ON Products (Productimage);
CREATE UNIQUE INDEX Code_UNIQUE ON Products (Code);



-- -----------------------------------------------------
-- Table Orders
-- -----------------------------------------------------
DROP TABLE IF EXISTS Orders CASCADE;

CREATE TABLE IF NOT EXISTS Orders (
  idOrders SERIAL,
  CustomerID INT NOT NULL,
  Orderdate TIMESTAMP NOT NULL,
  Subtotal DECIMAL(16,2) NOT NULL,
  Shipping DECIMAL(16,2) NULL,
  Taxes DECIMAL(16,2) NULL,
  Total DECIMAL(16,2) NOT NULL,
  OrderStatus VARCHAR(64) NOT NULL,
  Tracking VARCHAR(64) NULL,
  BillingAddress VARCHAR(256) NULL,
  ShippingAddress VARCHAR(256) NOT NULL,
  AddressSame BOOLEAN NOT NULL,
  PRIMARY KEY (idOrders),
  CONSTRAINT fk_Customer_id FOREIGN KEY (CustomerID)
    REFERENCES Customers (idCustomers)
);



-- -----------------------------------------------------
-- Table Addresses
-- -----------------------------------------------------
DROP TABLE IF EXISTS Addresses CASCADE;

CREATE TABLE IF NOT EXISTS Addresses (
  idAddresses SERIAL,
  CustomerID INT NOT NULL,
  Street_L1 VARCHAR(128) NOT NULL,
  Street_L2 VARCHAR(128) NULL,
  City VARCHAR(128) NOT NULL,
  USState CHAR(2) NOT NULL,
  Zipcode INT NOT NULL,
  Zip_4 INT NULL,
  PRIMARY KEY (idAddresses),
  CONSTRAINT fk_Customer_id FOREIGN KEY (CustomerID)
    REFERENCES Customers (idCustomers)
);


-- -----------------------------------------------------
-- Table Saved_Payment
-- -----------------------------------------------------
DROP TABLE IF EXISTS Saved_Payment CASCADE;

CREATE TABLE IF NOT EXISTS Saved_Payment (
  idSaved_Payment SERIAL,
  CustomerID INT NOT NULL,
  cardtype VARCHAR(8) NOT NULL,
  cvc SMALLINT NOT NULL,
  cardnumber VARCHAR(16) NOT NULL,
  cardzip INT NOT NULL,
  PRIMARY KEY (idSaved_Payment),
  CONSTRAINT fk_Customer_id FOREIGN KEY (CustomerID)
    REFERENCES Customers (idCustomers)
);


-- -----------------------------------------------------
-- Table OrderProduct
-- -----------------------------------------------------
  DROP TABLE IF EXISTS OrderProduct CASCADE;

  CREATE TABLE IF NOT EXISTS OrderProduct (
    idOrderProduct SERIAL,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    PRIMARY KEY (idOrderProduct),
    CONSTRAINT fk_order
      FOREIGN KEY (OrderID)
      REFERENCES Orders (idOrders),
    CONSTRAINT fk_product
      FOREIGN KEY (ProductID)
      REFERENCES Products (idProducts)
  );


